int crunch(void) {
	system("clear");
	puts("WWWWWWWWWWWWWWWW");
	puts(" ");
	puts(" ");
	puts(" ");
	puts(" ");
	puts(" ");
	puts(" ");
	puts("MMMMMMMMMMMMMMMM");
	sleep(1);
	system("clear");
	puts("WWWWWWWWWWWWWWWW");
	puts(" ");
	puts(" ");
	puts(" ");
	puts(" ");
	puts(" ");
	puts("MMMMMMMMMMMMMMMM");
	sleep(1);
	system("clear");
	puts("WWWWWWWWWWWWWWWW");
	puts(" ");
	puts(" ");
	puts(" ");
	puts(" ");
	puts("MMMMMMMMMMMMMMMM");
	sleep(1);
	system("clear");
	puts("WWWWWWWWWWWWWWWW");
	puts(" ");
	puts(" ");
	puts(" ");
	puts("MMMMMMMMMMMMMMMM");
	sleep(1);
	system("clear");
	puts("WWWWWWWWWWWWWWWW");
	puts(" ");
	puts(" ");
	puts("MMMMMMMMMMMMMMMM");
	sleep(1);
	system("clear");
	puts("WWWWWWWWWWWWWWWW");
	puts(" ");
	puts("MMMMMMMMMMMMMMMM");
	sleep(1);
	system("clear");
	puts("WWWWWWWWWWWWWWWW");
	puts("MMMMMMMMMMMMMMMM");
	sleep(1);
	system("clear");
	puts("CRUNCH!");
	sleep(1);
	system("clear");
}
